# Generated by Django 2.0.7 on 2018-08-01 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tsuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='TSUser',
        ),
    ]
