# Generated by Django 2.0.7 on 2018-08-08 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tsuser',
            name='active',
        ),
    ]
