# Generated by Django 2.0.7 on 2018-08-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_remove_tsuser_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsuser',
            name='role',
            field=models.CharField(choices=[('SK', 'Stallkeeper'), ('SA', 'Stall Admin')], max_length=2),
        ),
    ]
