# Generated by Django 2.0.7 on 2018-08-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
