# Generated by Django 2.0.7 on 2018-08-03 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('itemmanager', '0002_auto_20180802_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='availability',
            new_name='item_availability',
        ),
        migrations.RemoveField(
            model_name='restock',
            name='item',
        ),
        migrations.RemoveField(
            model_name='restock',
            name='restock_amount',
        ),
        migrations.RemoveField(
            model_name='restock',
            name='restock_cost',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='item',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sale_amount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sale_price_custom',
        ),
        migrations.AddField(
            model_name='restock',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='restock',
            name='restock_proof_of_payment',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
