# Generated by Django 2.0.7 on 2018-08-03 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmanager', '0003_auto_20180803_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestockItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restock_item_amount', models.PositiveIntegerField()),
                ('restock_item_total_cost', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemmanager.Item')),
                ('restock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemmanager.Restock')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_amount', models.PositiveIntegerField()),
                ('sale_price', models.FloatField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemmanager.Item')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemmanager.Sale')),
            ],
        ),
    ]
