# Generated by Django 2.0.7 on 2018-08-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemmanager', '0005_auto_20180807_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterUniqueTogether(
            name='restockitem',
            unique_together={('restock', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='saleitem',
            unique_together={('sale', 'item')},
        ),
    ]
