# Generated by Django 2.0.7 on 2018-08-22 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmanager', '0006_auto_20180808_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_stock',
        ),
    ]
