# Generated by Django 2.0.7 on 2018-08-23 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmanager', '0007_remove_item_item_stock'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saleitem',
            unique_together=set(),
        ),
    ]
