# Generated by Django 2.0.7 on 2018-08-23 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmanager', '0008_auto_20180823_1832'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='restockitem',
            unique_together=set(),
        ),
    ]
