# Generated by Django 2.0.7 on 2018-08-23 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemmanager', '0009_auto_20180823_1832'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='restockitem',
            unique_together={('restock', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='saleitem',
            unique_together={('sale', 'item')},
        ),
    ]
