# Generated by Django 2.0.7 on 2018-08-29 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itemmanager', '0010_auto_20180823_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restock',
            name='restock_PIC',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
