# Generated by Django 2.0.7 on 2018-07-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
