# Generated by Django 2.0.7 on 2018-07-31 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsmanager', '0002_auto_20180731_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restock_amount', models.IntegerField()),
                ('restock_cost', models.FloatField()),
                ('in_charge', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restock',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsmanager.Item'),
        ),
    ]
