# Generated by Django 2.0.7 on 2018-07-31 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsmanager', '0003_auto_20180731_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restock',
            old_name='in_charge',
            new_name='PIC',
        ),
    ]
