# Generated by Django 2.0.7 on 2018-07-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsmanager', '0005_auto_20180801_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='custom_price',
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_price_custom',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
