# Generated by Django 2.0.7 on 2018-07-31 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsmanager', '0007_auto_20180801_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempricehistory',
            name='item',
        ),
        migrations.DeleteModel(
            name='ItemPriceHistory',
        ),
    ]
